### ISSUE TITLE
[REQ] WinForms Support

### ISSUE THREAD

**Issue by reinoma** [Laamy/LightDocumentats#2]
It possible to support WinForms Application like KrnlApi on Roblox will do?

**Comment by Laamy** [comment]
I'll make a managed API for that if you really want it

**Comment by Laamy** [comment]
I was originally planning on it being smth u could script in lua then compile to an injectable DLL instead of an actual full out live lua executor

**Comment by reinoma** [comment]
But source code of Light Api it gonna close source or open source?

**Comment by Laamy** [comment]
Closed source but something you can program clients with and keep obfuscated/hidden
